### ISSUE TITLE
Python 2.6 does not have subprocess.check_output()

### ISSUE THREAD

**Issue by rferris** [SECFORCE/sparta#7]
Not sure if it's something you guys would want to fix, but Centos/RHEL6 can't run this due to not having Python 2.7. I've not attempted a workaround and know that Centos 6 is pretty old, but thought I'd bring it up in case others are confused/having trouble.

**Comment by rferris** [comment]
Traceback is:

Traceback (most recent call last):
  File "./sparta.py", line 81, in <module>
    logic = Logic()                                                                     # Model prep (logic, db and models)
  File "/home/rferris/build/sparta/app/logic.py", line 23, in __init__
    self.cwd = subprocess.check_output("echo $OLDPWD", shell=True)[:-1]+'/'
AttributeError: 'module' object has no attribute 'check_output'

**Comment by st3r30byt3** [comment]
Thanks for the feedback Rohan. We mostly focused on making SPARTA work in Kali Linux (and Python 2.7) as we feel this is the most 'convenient' environment to run it from: all the tools are there, it runs as root which is helpful for some nmap options, etc. However, if there is an easy fix we are happy to include it in the next commit. We'll investigate and I'll leave the issue open in case anyone else finds a fix.

**Comment by rferris** [comment]
No worries. I definitely understand. I did backport the check_output function and got past that error, but then I wound up with PyQT4 issues that seem to be due to the older libs. If I get a chance to debug that I'll let you know. With how good this tool looks, I'm sure others on other distros will be keen to use it too. :)

**Comment by st3r30byt3** [comment]
Closed. At this point we are solely focused on Kali.
